# Generated by Django 3.2.3 on 2021-11-11 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 10, 59, 5, 204389)),
        ),
    ]
