# Generated by Django 3.2.3 on 2021-11-11 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_quote_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
