# Generated by Django 3.2.3 on 2021-11-13 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211113_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 16, 6, 31, 943921)),
        ),
    ]
