# Generated by Django 3.2.3 on 2021-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_quote_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
